name: Run UHI Script Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Jam 03:20 WITA = 19:20 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run UHI script
        run: python uhi_fetcher.py

      - name: Commit and push results
        run: |
          git config --global user.name "PlaneFly545"
          git config --global user.email "prabawasandi545@gmail.com"
          git pull origin main
          git add uhi_result.json uhi_log.txt
          git commit -m "Update UHI data" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
