name: Run UHI Script Daily

on:
  schedule:
    - cron: '35 17 * * *'  
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run UHI script
        run: python uhi_fetcher.py

      - name: Commit and push results
        run: |
          git config --global user.name "PlaneFly545"
          git config --global user.email "prabawasandi545@gmail.com"
          git add uhi_result.json uhi_log.txt
          git commit -m "Update UHI data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Menambahkan GITHUB_TOKEN
