name: Run UHI Script Daily

on:
  schedule:
    - cron: '30 0 * * *'  # Setiap hari jam 07.30 WIB (WIB = UTC+7 → cron pakai UTC)
  workflow_dispatch:  # Bisa dijalankan manual juga dari GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run UHI script
        run: python uhi_fetcher.py

      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Menambahkan GITHUB_TOKEN
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add uhi_result.json uhi_log.txt
          git commit -m "Update UHI data" || echo "No changes to commit"
          git push
